# Generated by Django 4.1.1 on 2022-09-24 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='public',
            field=models.BooleanField(default=1),
        ),
        migrations.AddField(
            model_name='photo',
            name='public',
            field=models.BooleanField(default=1),
        ),
    ]
