# Generated by Django 4.1.1 on 2022-09-24 07:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0002_album_public_photo_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='fav',
            field=models.ManyToManyField(blank=True, related_name='fav', to=settings.AUTH_USER_MODEL),
        ),
    ]
