# Generated by Django 4.1.1 on 2022-09-24 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_photo_fav'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'verbose_name': 'albums', 'verbose_name_plural': 'albums'},
        ),
        migrations.AlterModelTable(
            name='album',
            table='albums',
        ),
    ]
