# Generated by Django 4.1.1 on 2022-09-24 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_alter_album_options_alter_album_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={},
        ),
        migrations.AlterModelTable(
            name='album',
            table=None,
        ),
    ]
